name: CI/CD

on:
  push:
    branches:
       -main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Specify your AWS region


      - name: Install dependencies
        run: |
          USER_DATA=$(base64 -w 0 <<EOF
          #!/bin/bash
          sudo apt update
          curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh
          bash -E nodesource_setup.sh
          sudo apt install nodejs -y
          npm install -g yarn
          echo -e "skip\n" | yarn create-strapi-app Strapi_app --quickstart
          EOF
          )
      - name: Deploy with PM2
        run: |
          yarn install 
          yarn build
          pm2 start npm --name "Strapi_app" -- start
        working-directory: ./home/ubuntu/Strapi_app # Ensure this points to the correct directory