name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main  # Trigger on push to the main branch, adjust as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client


      - name: SSH and Deploy Strapi
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          KEY_PATH: ${{ secrets.KEY_PATH }}
        run: cd /home/ubuntu/srv/strapi && npm run build

